name: Run the tests

on: [pull_request]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: oracle

      - name: Install dependencies
        run: mvn clean install -DskipTests=true --no-transfer-progress

      - name: Install test dependencies
        run: mvn test -DskipTests=true --no-transfer-progress

  tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_class:
          # Codecs
          - "com.ex_dock.ex_dock.codecs.**"

          # backend
          - "com.ex_dock.ex_dock.backend.**"

          # frontend
          - "com.ex_dock.ex_dock.frontend.**"

          # database
          - "com.ex_dock.ex_dock.database.**"


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: oracle

      - name: Run Tests
        run: |
          docker compose -f .ci/compose.yaml -p ci up -d --quiet-pull
          mvn -Dtest=${{ matrix.test_class }} test --no-transfer-progress -e
